name: flutter_widget_resources
description: "Flutter Widget Resources"

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  sizer: ^2.0.15
  intl: ^0.18.1
  get: ^4.6.6
  http: ^0.13.5
  #google_generative_ai: ^0.4.4
  #flutter_svg: ^1.1.6

  #fluttertoast: ^8.1.2
  #pin_code_fields: ^7.4.0
  #shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

